### ISSUE TITLE
Intel Galileo Gen 2

### ISSUE THREAD

**Issue by indiependente** [tokoro10g/galileo-makefile#3]
Hi,
I've tried to port your Makefile in order to make it work with the Galileo Gen 2.
The compilation is fine, but when I copy the executable on the board and try to run (after chmod +x), it says "-sh: ./helloworld: No such file or directory".
Just like when happens to run a 32bits executable on a 64 bits machine.

Do you have any advice I could follow?
Thanks in advance

**Comment by tokoro10g** [comment]
Hi, thanks for reporting the issue!

Perhaps that is due to a mismatch of libc; you are using eglibc-based linux image, while the libc in Arduino IDE is uclibc-based, and vice versa.
Which linux image for Galileo are you using? Does an Arduino sketch work fine on your Galileo?

Anyway, can you provide some logs while compiling?
Also, pasting diff here would be appreciated if you have changed Makefile.

**Comment by indiependente** [comment]
Before setting up the Linux image, I was using the board by pushing the sketch via Arduino 1.5.3 - Intel 1.0.4 (Mac OS X version) provided at https://downloadcenter.intel.com/download/24357/Intel-Edison-software-package-1-0-4 (I know it's Edison but is the only version that I've seen doing the job with some example sketches and a program I made).
Then I set up the Linux image provided here: http://www.intel.com/support/galileo/sb/CS-035101.htm

Makefile diff:

``` diff
3,7c3,5
< # NATIVE_NAME = x86_64-pokysdk-linux
< # TARGET_NAME = core2-32-poky-linux
< TARGET_NAME = i586-poky-linux
< NATIVE_NAME = i386-pokysdk-darwin
< GCC_VERSION = 4.8.2
---
> TARGET_NAME = i586-poky-linux-uclibc
> NATIVE_NAME = x86_64-pokysdk-linux
> GCC_VERSION = 4.7.2
24c22
< CC      = $(TOOLDIR)/i586-poky-linux-g++
---
> CC      = $(TOOLDIR)/i586-poky-linux-uclibc-g++
28c26
< AR      = $(TOOLDIR)/i586-poky-linux-ar
---
> AR      = $(TOOLDIR)/i586-poky-linux-uclibc-ar
39c37
<   rm -f $(TARGET_BIN) *.o
---
>   rm -f $(TARGET_BIN) *.o
\ No newline at end of file
```

Compile log:

```
/opt/clanton-tiny/1.4.2/sysroots/i386-pokysdk-darwin//usr/bin/i586-poky-linux/i586-poky-linux-g++ -O2 -pipe -g -feliminate-unused-debug-types -fpermissive -Wall -I /opt/clanton-tiny/1.4.2/sysroots/i586-poky-linux//usr/include -I /opt/clanton-tiny/1.4.2/sysroots/i586-poky-linux//usr/include/c++ -I /opt/clanton-tiny/1.4.2/sysroots/i386-pokysdk-darwin//usr/lib/i586-poky-linux/gcc/i586-poky-linux/4.8.2/include  -m32 -march=i586 --sysroot=/opt/clanton-tiny/1.4.2/sysroots/i586-poky-linux/ -c -o helloworld.o helloworld.c
/opt/clanton-tiny/1.4.2/sysroots/i386-pokysdk-darwin//usr/bin/i586-poky-linux/i586-poky-linux-g++ -Wl,-O1 -Wl,--hash-style=gnu -Wl,--as-needed -L /opt/clanton-tiny/1.4.2/sysroots/i586-poky-linux//lib -L /opt/clanton-tiny/1.4.2/sysroots/i586-poky-linux//usr/lib -L /opt/clanton-tiny/1.4.2/sysroots/i586-poky-linux//usr/lib/i586-poky-linux/4.8.2 -lstdc++ -m32 -march=i586 --sysroot=/opt/clanton-tiny/1.4.2/sysroots/i586-poky-linux/ helloworld.o -o helloworld
```

Thanks for your support.

EDIT

Should I try with this? http://downloadmirror.intel.com/24783/eng/IntelArduino-1.6.0-OSX.zip

**Comment by tokoro10g** [comment]
Thanks for the information.

Edison and Galileo is not compatible AFAIK, so you should use the [Galileo version of Arduino IDE](https://downloadcenter.intel.com/download/24782) (v 1.5.3 is supported by this Makefile).
The suffix "-uclibc" means the compiler was built against uclibc which Intel's linux image uses.

Try Intel Arduino IDE 1.5.3 and follow the instructions in README.
You will only have to change `NATIVE_NAME` in order to use with OSX.
Then, it should work :smile:

**Comment by indiependente** [comment]
It worked like a charm!
Thank you so much :D

I'm posting how I did it to help others with my same problem.
The steps I did were:
- Download the Arduino IDE provided in your post
- `cd hardware/tools/i586`
- `sudo cp -R i586-poky-linux-uclibc /opt/clanton-tiny/1.4.2/sysroots/`
- `sudo cp -R pokysdk /opt/clanton-tiny/1.4.2/sysroots/`
- `cd /opt/clanton-tiny/1.4.2/sysroots/`
- `sudo mv pokysdk x86_64-pokysdk-linux`
- Place yourself under your project dir and `make` ;)

Cheers :beers:

**Comment by tokoro10g** [comment]
Yay! Enjoy :smiley_cat:
